# TODO: how to properly implement zelda/sheik vs zelda vs sheik based on mode
# have to fix zelda/sheik, maybe move to bottom
BTT_CHARACTERS = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "Donkey Kong",
    "Captain Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Popo",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda/Sheik",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. Game & Watch",
    "Marth",
    "Roy",
    "Zelda",
    "Sheik",    
    "Male Wireframe",
    "Female Wireframe",
    "Giga Bowser",
    "Master Hand",
    "Crazy Hand"
]

BTT_CHARS_STAGE_COMMAND = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "Donkey Kong",
    "Captain Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Popo",
    "Kirby",
    "Samus",
    "Sheik",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. Game & Watch",
    "Marth",
    "Roy",
]

BTT_STAGES = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "Donkey Kong",
    "Captain Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. Game & Watch",
    "Marth",
    "Roy",
    "Seak"
]

BTT_SUS_TAGS = {
    'bair' : 'Back Aerial Only',
    'dair' : 'Down Aerial Only',
    'nair' : 'Neutral Aerial Only',
    'fair' : 'Forward Aerial Only',
    'uair' : 'Up Aerial Only',
    'nb' : 'Neutral B Only',
    'fb' : 'Forward B Only',
    'upb' : 'Up B Only',
    'downb' : 'Down B Only',
    'BMO' : 'B Moves Only',
    'AMO' : 'A Moves Only',
    'LTA' : 'Limited Time Attack',
    'FRO' : 'Facing Right Only',
    'RWO' : 'Reverse World Record Order',
    'TTB' : 'Top to Bottom',
    'BTT' : 'Bottom to Top',
    'RTL' : 'Right to Left',
    'LTR' : 'Left to Right',
    'BSS' : 'Bottom Side Suicide',
    'RSS' : 'Right Side Suicide',
    'TSS' : 'Top Side Suicide',
    'LSS' : 'Left Side Suicide',
    'NCS' : 'No Control Stick',
    'NJA' : 'No Jump Allowed',
    'OHO' : 'One Hand Only',
    '1T' : 'One Target (T10 of current WR)',
    '999%' : 'Attain 999% Damage and complete the stage',
    'zair' : 'Hookshot/grapple only',
    'misfire' : 'Misfire only (no code)',
    # 'Mismatch' : 'Char != Stage',
    'AR' : "Action Replay / Gecko Coded Runs",
    'Grounded' : 'All targets must be broken while grounded', # double check this definition
    'Riddle' : 'tbd',
    'Ledge Riddle' : 'tbd',
    'Riddle Glitchless' : 'tbd',
    'FZI' : 'Fully Zoomed In',
    'blindfolded' : 'Blindfolded run',


    # 'NCS BSS' # NCS is its own categore, make sure NCS runs dont get categorized with suicide runs or completions
    # e.g. if a NCS luigi exists, make sure the separate NCS and BSS tags dont interfere with it.   
    # 'no upb, no air dodge, 9 targets (x targets), no neuitral b, mr saturn, beam sword, bomb, no turnips, ar bomb, ar pokebolls , no upb, no pressing down, no nb,  '
    # 'top target first, all blocks/targets, no glitch'
    # 'full charge shot, bomb riddle', 'only zelda,', '5 ze 5sheik', 'no forward b', 'no projectiles hookshot','no damage', ''
    
}
