HRC_CHARACTERS = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "Donkey Kong",
    "Captain Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda/Sheik",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. Game & Watch",
    "Marth",
    "Roy",
    "Zelda",
    "Sheik"
]

HRC_SUS_TAGS = {
    'NBA' : 'No Bat Allowed',
    'NBD' : 'No Bat Drops',
    'BMO' : 'B Moves Only',
    'NJA' : 'No Jump Allowed',
    'LTA' : 'Limited Time Attack',
    'Falcon Bat Swing' : 'Use Falcon Bat Swing to hit Sandbag at end',
    'AAA' : 'All Aerial Attacks',
}