PERSONAL_GUILD_ID = 977851191088267274
STADIUM_GUILD_ID = 132025591770644480
GUILD_IDS = [PERSONAL_GUILD_ID, STADIUM_GUILD_ID]

# TODO: how to properly implement zelda/sheik vs zelda vs sheik based on mode
TENMM_CHARACTERS = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "DK",
    "Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. G&W",
    "Marth",
    "Roy",
    "Sheik",
    "Zelda/Sheik"
    "Popo",
    "M. Wireframe",
    "F. Wireframe",
    "Giga Bowser",
    "Master Hand",
    "Crazy Hand",
    "Sandbag",
]

HRC_CHARACTERS = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "Donkey Kong",
    "Captain Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda/Sheik",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. Game & Watch",
    "Marth",
    "Roy",
    "Zelda",
    "Sheik"
]

BTT_CHARACTERS = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "Donkey Kong",
    "Captain Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Popo",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda/Sheik",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. Game & Watch",
    "Marth",
    "Roy",
    "Zelda",
    "Sheik",    
    "Male Wireframe",
    "Female Wireframe",
    "Giga Bowser",
    "Master Hand",
    "Crazy Hand"
]

BTT_STAGES = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "Donkey Kong",
    "Captain Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. Game & Watch",
    "Marth",
    "Roy",
    "Seak",
]

VERSIONS = [
    "NTSC1.00",
    "NTSC1.01",
    "NTSC1.02",
    "PAL"
]

EVENTS = [
    "Trouble King", 
    "Lord of the Jungle",
    "Bomb-fest",
    "Dino-wrangling",
    "Spare Change",
    "Kirbys on Parade",
    "Pokémon Battle",
    "Hot Date on Brinstar",
    "Hide 'n' Sheik",
    "All-Star Match 1",
    "King of the Mountain",
    "Seconds, Anyone?",
    "Yoshi's Egg",
    "Trophy Tussle 1",
    "Girl Power",
    "Kirby's Air-raid",
    "Bounty Hunters",
    "Link's Adventure",
    "Peach's Peril",
    "All-Star Match 2",
    "Ice Breaker",
    "Super Mario 128",
    "Slippy's Invention",
    "The Yoshi Herd",
    "Gargantuans",
    "Trophy Tussle 2",
    "Cold Armor",
    "Pluffballs Unite!",
    "Triforce Gathering",
    "All-Star Match 3",
    "Mario Bros. Madness",
    "Target Acquired",
    "Lethal Marathon",
    "Seven Years",
    "Time for a Checkup",
    "Space Travelers",
    "Legendary Pokémon",
    "Super Mario Bros. 2",
    "Jigglypuff Live!",
    "All-Star Match 4",
    "En Garde!",
    "Trouble King 2",
    "Birds of Prey",
    "Mewtwo Strikes",
    "Game & Watch Forever!", 
    "Fire Emblem Pride", 
    "Trophy Tussle 3",
    "Pikachu and Pichu",
    "All-Star Match Deluxe",
    "Final Destination Match",
    "The Showdown"
]

# AKANEIA_CHARACTERS_STAGES = [
#     "Wolf",
#     "Diddy Kong",
#     "Charizard"
# ]
# TODO: add akaneia versions
# AKANEIA_VERSIONS = [ see akaneia github ]

ALIASES = {
    # alias : char_name
    'Dr. Mario' : 'Dr. Mario',
    'doc' : 'Dr. Mario',
    'dr.' : 'Dr. Mario',
    'doctor mario': 'Dr. Mario',
    'Mario' : 'Mario',
    'Luigi' : 'Luigi',
    'Bowser' : 'Bowser',
    'Peach' : 'Peach',
    'Yoshi' : 'Yoshi',
    'Donkey Kong': 'Donkey Kong',
    'dk' : 'Donkey Kong',
    'Captain Falcon' : 'Captain Falcon',
    'Falcon' : 'Captain Falcon',
    'cf' : 'Captain Falcon',
    'Ganondorf' : 'Ganondorf',
    'ganon' : 'Ganondorf',
    'Falco' : 'Falco',
    'Fox' : 'Fox',
    'Ness' : 'Ness',
    'Popo' : 'Popo', # add alias check when selecting sopo as stage name?
    'sopo' : 'Popo', 
    'ic' : 'Popo', 
    'Kirby' : 'Kirby',
    'Samus' : 'Samus',
    'Sheik' : 'Sheik',
    'Link' : 'Link',
    'link' : 'Link',
    'Young Link' : 'Young Link',
    'yl' : 'Young Link',
    'yink' : 'Young Link',
    'ylink' : 'Young Link',
    'Pichu' : 'Pichu',
    'Pikachu' : 'Pikachu',
    'pika' : 'Pikachu',
    'Jigglypuff' : 'Jigglypuff',
    'jiggs' : 'Jigglypuff',
    'puff' : 'Jigglypuff',
    'Mewtwo' : 'Mewtwo',
    'm2' : 'Mewtwo',
    'Mr. Game & Watch' : 'Mr. Game & Watch',
    'g&w' : 'Mr. Game & Watch',
    'gw' : 'Mr. Game & Watch',
    'Marth' : 'Marth',
    'Roy' : 'Roy',
    'Zelda/Sheik' : 'Zelda/Sheik',
    'z/s' : "Zelda/Sheik",
    'Zelda' : 'Zelda',
    'Ice Climbers' : 'Ice Climbers',
    'ics' : 'Ice Climbers',
    'Giga Bowser' : 'Giga Bowser', 
    'giga' : 'Giga Bowser',
    'Male Wireframe' : 'Male Wireframe',
    'mwf' : 'Male Wireframe',
    'Female Wireframe' : 'Female Wireframe',
    'fwf' : 'Female Wireframe',
    'Master Hand' : 'Master Hand',
    'mh' : 'Master Hand',
    'Crazy Hand' : 'Crazy Hand',
    'ch' : 'Crazy Hand',
    'Seak' : 'Seak',
    'seak' : 'Seak',
}

HRC_SUS_TAGS = {
    'NBA' : 'No Bat Allowed',
    'NBD' : 'No Bat Drops',
    'BMO' : 'B Moves Only',
    'NJA' : 'No Jump Allowed',
    'LTA' : 'Limited Time Attack',
    'Falcon Bat Swing' : 'Use Falcon Bat Swing to hit Sandbag at end',
    'AAA' : 'All Aerial Attacks',
}

BTT_SUS_TAGS = {
    'bair' : 'Back Aerial Only',
    'dair' : 'Down Aerial Only',
    'nair' : 'Neutral Aerial Only',
    'fair' : 'Forward Aerial Only',
    'uair' : 'Up Aerial Only',
    'nb' : 'Neutral B Only',
    'fb' : 'Forward B Only',
    'upb' : 'Up B Only',
    'downb' : 'Down B Only',
    'BMO' : 'B Moves Only',
    'AMO' : 'A Moves Only',
    'LTA' : 'Limited Time Attack',
    'FRO' : 'Facing Right Only',
    'RWO' : 'Reverse World Record Order',
    'TTB' : 'Top to Bottom',
    'BTT' : 'Bottom to Top',
    'RTL' : 'Right to Left',
    'LTR' : 'Left to Right',
    'BSS' : 'Bottom Side Suicide',
    'RSS' : 'Right Side Suicide',
    'TSS' : 'Top Side Suicide',
    'LSS' : 'Left Side Suicide',
    'NCS' : 'No Control Stick',
    'NJA' : 'No Jump Allowed',
    'OHO' : 'One Hand Only',
    '1T' : 'One Target (T10 of current WR)',
    '999%' : 'Attain 999% Damage and complete the stage',
    'zair' : 'Hookshot/grapple only',
    'misfire' : 'Misfire only (no code)',
    # 'Mismatch' : 'Char != Stage',
    'AR' : "Action Replay / Gecko Coded Runs",
    'Grounded' : 'All targets must be broken while grounded', # double check this definition
    'Riddle' : 'tbd',
    'Ledge Riddle' : 'tbd',
    'Riddle Glitchless' : 'tbd',
    'FZI' : 'Fully Zoomed In',
    'blindfolded' : 'Blindfolded run',


    # 'NCS BSS' # NCS is its own categore, make sure NCS runs dont get categorized with suicide runs or completions
    # e.g. if a NCS luigi exists, make sure the separate NCS and BSS tags dont interfere with it.   
    # 'no upb, no air dodge, 9 targets (x targets), no neuitral b, mr saturn, beam sword, bomb, no turnips, ar bomb, ar pokebolls , no upb, no pressing down, no nb,  '
    # 'top target first, all blocks/targets, no glitch'
    # 'full charge shot, bomb riddle', 'only zelda,', '5 ze 5sheik', 'no forward b', 'no projectiles hookshot','no damage', ''
    
}

TENMM_SUS_TAGS = {
    'OHKO' : 'One-Hit KO (modified moves)',
    'Throw' : 'Throw Only',
}

EVENT_SUS_TAGS = {
    'OHO' : 'One Hand Only',
}