PERSONAL_GUILD_ID = 977851191088267274
STADIUM_GUILD_ID = 132025591770644480

# TODO: how to properly implement zelda/sheik vs zelda vs sheik based on mode
TENMM_CHARACTERS = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "DK",
    "Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. G&W",
    "Marth",
    "Roy",
    "Sheik",
    "Zelda/Sheik"
    "Popo",
    "M. Wireframe",
    "F. Wireframe",
    "Giga Bowser",
    "Master Hand",
    "Crazy Hand",
    "Sandbag",
]

HRC_CHARACTERS = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "Donkey Kong",
    "Captain Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Zelda/Sheik",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. Game & Watch",
    "Marth",
    "Roy",
    "Zelda",
    "Sheik"
]

BTT_STAGES = [
    "Dr. Mario",
    "Mario",
    "Luigi",
    "Bowser",
    "Peach",
    "Yoshi",
    "DK",
    "Falcon",
    "Ganondorf",
    "Falco",
    "Fox",
    "Ness",
    "Ice Climbers",
    "Kirby",
    "Samus",
    "Sheik",
    "Link",
    "Young Link",
    "Pichu",
    "Pikachu",
    "Jigglypuff",
    "Mewtwo",
    "Mr. G&W",
    "Marth",
    "Roy",
    "Seak",
]

VERSIONS = [
    "NTSC1.00",
    "NTSC1.01",
    "NTSC1.02",
    "PAL"
]

EVENTS = [
    "Trouble King", 
    "Lord of the Jungle",
    "Bomb-fest",
    "Dino-wrangling",
    "Spare Change",
    "Kirbys on Parade",
    "Pokémon Battle",
    "Hot Date on Brinstar",
    "Hide 'n' Sheik",
    "All-Star Match 1",
    "King of the Mountain",
    "Seconds, Anyone?",
    "Yoshi's Egg",
    "Trophy Tussle 1",
    "Girl Power",
    "Kirby's Air-raid",
    "Bounty Hunters",
    "Link's Adventure",
    "Peach's Peril",
    "All-Star Match 2",
    "Ice Breaker",
    "Super Mario 128",
    "Slippy's Invention",
    "The Yoshi Herd",
    "Gargantuans",
    "Trophy Tussle 2",
    "Cold Armor",
    "Pluffballs Unite!",
    "Triforce Gathering",
    "All-Star Match 3",
    "Mario Bros. Madness",
    "Target Acquired",
    "Lethal Marathon",
    "Seven Years",
    "Time for a Checkup",
    "Space Travelers",
    "Legendary Pokémon",
    "Super Mario Bros. 2",
    "Jigglypuff Live!",
    "All-Star Match 4",
    "En Garde!",
    "Trouble King 2",
    "Birds of Prey",
    "Mewtwo Strikes",
    "Game & Watch Forever!", 
    "Fire Emblem Pride", 
    "Trophy Tussle 3",
    "Pikachu and Pichu",
    "All-Star Match Deluxe",
    "Final Destination Match",
    "The Showdown"
]

# AKANEIA_CHARACTERS_STAGES = [
#     "Wolf",
#     "Diddy Kong",
#     "Charizard"
# ]
# TODO: add akaneia versions
# AKANEIA_VERSIONS = [ see akaneia github ]

ALIASES = {
    # alias : char_name
    'Dr. Mario' : 'Dr. Mario',
    'doc' : 'Dr. Mario',
    'dr.' : 'Dr. Mario',
    'doctor mario': 'Dr. Mario',
    'Mario' : 'Mario',
    'Luigi' : 'Luigi',
    'Bowser' : 'Bowser',
    'Peach' : 'Peach',
    'Yoshi' : 'Yoshi',
    'Donkey Kong': 'Donkey Kong',
    'dk' : 'Donkey Kong',
    'Captain Falcon' : 'Captain Falcon',
    'Falcon' : 'Captain Falcon',
    'cf' : 'Captain Falcon',
    'Ganondorf' : 'Ganondorf',
    'ganon' : 'Ganondorf',
    'Falco' : 'Falco',
    'Fox' : 'Fox',
    'Ness' : 'Ness',
    'Popo' : 'Popo', # add alias check when selecting sopo as stage name?
    'sopo' : 'Popo', 
    'ic' : 'Popo', 
    'Kirby' : 'Kirby',
    'Samus' : 'Samus',
    'Sheik' : 'Sheik',
    'Link' : 'Link',
    'Young Link' : 'Young Link',
    'yl' : 'Young Link',
    'ylink' : 'Young Link',
    'Pichu' : 'Pichu',
    'Pikachu' : 'Pikachu',
    'pika' : 'Pikachu',
    'Jigglypuff' : 'Jigglypuff',
    'jiggs' : 'Jigglypuff',
    'puff' : 'Jigglypuff',
    'Mewtwo' : 'Mewtwo',
    'm2' : 'Mewtwo',
    'Mr. Game & Watch' : 'Mr. Game & Watch',
    'g&w' : 'Mr. Game & Watch',
    'gw' : 'Mr. Game & Watch',
    'Marth' : 'Marth',
    'Roy' : 'Roy',
    'Zelda/Sheik' : 'Zelda/Sheik',
    'z/s' : "Zelda/Sheik",
    'Zelda' : 'Zelda',
    'Ice Climbers' : 'Ice Climbers',
    'ics' : 'Ice Climbers',
    'Giga Bowser' : 'Giga Bowser', 
    'giga' : 'Giga Bowser',
    'Male Wireframe' : 'Male Wireframe',
    'mwf' : 'Male Wireframe',
    'Female Wireframe' : 'Female Wireframe',
    'fwf' : 'Female Wireframe',
    'Master Hand' : 'Master Hand',
    'mh' : 'Master Hand',
    'Crazy Hand' : 'Crazy Hand',
    'ch' : 'Crazy Hand'
}